import React, { useEffect, useMemo, useRef, useState } from 'react';
import MaintenanceCalendar from '../components/MaintenanceCalendar.jsx';

const backendURL = import.meta.env.VITE_BACKEND_URL?.replace(/\/$/, '');

// Local storage for tickets when backend is not available
const DASHBOARD_STATE_KEY = 'dashboard:state';
function readState() { try { return JSON.parse(localStorage.getItem(DASHBOARD_STATE_KEY) || '{}'); } catch { return {}; } }
function writeState(updater) {
  const current = readState();
  const next = typeof updater === 'function' ? updater(current) : { ...current, ...updater };
  localStorage.setItem(DASHBOARD_STATE_KEY, JSON.stringify(next));
  return next;
}

function generateTimes() {
  const times = [];
  const start = 8 * 60; // 8:00
  const end = 18 * 60; // 6:00 PM
  for (let m = start; m <= end; m += 30) {
    const h24 = Math.floor(m / 60);
    const min = m % 60;
    const ampm = h24 >= 12 ? 'PM' : 'AM';
    const h12 = ((h24 + 11) % 12) + 1;
    times.push(`${h12}:${min === 0 ? '00' : '30'} ${ampm}`);
  }
  return times;
}

// Sample machine list for autocomplete
const MACHINES = [
  { id: 'TM-001', name: 'Treadmill #1', type: 'Cardio' },
  { id: 'TM-002', name: 'Treadmill #2', type: 'Cardio' },
  { id: 'TM-003', name: 'Treadmill #3', type: 'Cardio' },
  { id: 'BP-001', name: 'Bench Press #1', type: 'Strength' },
  { id: 'BP-002', name: 'Bench Press #2', type: 'Strength' },
  { id: 'EL-001', name: 'Elliptical #1', type: 'Cardio' },
  { id: 'EL-002', name: 'Elliptical #2', type: 'Cardio' },
  { id: 'BK-001', name: 'Bike #1', type: 'Cardio' },
  { id: 'BK-002', name: 'Bike #2', type: 'Cardio' },
  { id: 'SR-001', name: 'Squat Rack #1', type: 'Strength' },
  { id: 'SR-002', name: 'Squat Rack #2', type: 'Strength' },
  { id: 'RM-001', name: 'Rowing Machine #1', type: 'Cardio' },
  { id: 'RM-002', name: 'Rowing Machine #2', type: 'Cardio' },
  { id: 'SM-001', name: 'Smith Machine #1', type: 'Strength' },
  { id: 'LP-001', name: 'Leg Press #1', type: 'Strength' },
];

// Component to highlight matching text
function HighlightMatch({ text, query }) {
  if (!query || !text) return <span>{text}</span>;
  
  const lowerText = text.toLowerCase();
  const lowerQuery = query.toLowerCase();
  const index = lowerText.indexOf(lowerQuery);
  
  if (index === -1) {
    return <span>{text}</span>;
  }
  
  const before = text.substring(0, index);
  const match = text.substring(index, index + query.length);
  const after = text.substring(index + query.length);
  
  return (
    <span>
      {before}
      <span className="tk-highlight">{match}</span>
      {after}
    </span>
  );
}

// Helper function to detect if a ticket is auto-generated
// Standardized detection logic - prioritizes explicit flags over patterns
function isAutoTicket(ticket) {
  // First, check explicit flags (most reliable)
  if (ticket.manual === true) return false;  // Explicitly manual
  if (ticket.manual === false) return true;  // Explicitly auto
  if (ticket.isAutoGenerated === true) return true;  // Auto flag
  
  // Second, check for auto ticket properties (rule-based)
  if (ticket.ruleKey != null || 
      ticket.ruleInterval != null || 
      ticket.intervalId != null) {
    return true;
  }
  
  // Third, pattern match for auto-generated descriptions (fallback)
  if (ticket.description && (
    ticket.description.includes('hours reached') ||
    ticket.description.includes('-hours service') ||
    ticket.description.includes('requires maintenance')
  )) {
    return true;
  }
  
  // Default to manual if unclear
  return false;
}

// Priority badge component
function PriorityBadge({ priority, size = 'small' }) {
  const priorityColors = {
    Low: { bg: 'rgba(59, 130, 246, 0.15)', color: '#93c5fd', border: 'rgba(59, 130, 246, 0.35)' },
    Medium: { bg: 'rgba(234, 179, 8, 0.15)', color: '#fde047', border: 'rgba(234, 179, 8, 0.35)' },
    High: { bg: 'rgba(239, 68, 68, 0.15)', color: '#fca5a5', border: 'rgba(239, 68, 68, 0.35)' }
  };
  const colors = priorityColors[priority] || priorityColors.Medium;
  const isSmall = size === 'small';
  
  return (
    <span style={{
      background: colors.bg,
      color: colors.color,
      border: `1px solid ${colors.border}`,
      borderRadius: '6px',
      fontSize: isSmall ? '10px' : '11px',
      fontWeight: '600',
      padding: isSmall ? '2px 6px' : '3px 8px',
      display: 'inline-flex',
      alignItems: 'center',
      lineHeight: 1,
      textTransform: 'uppercase',
      letterSpacing: '0.5px'
    }}>
      {priority || 'Medium'}
    </span>
  );
}

export default function TicketsTab() {
  const [tickets, setTickets] = useState([]);
  const [statuses, setStatuses] = useState([]);
  const [active, setActive] = useState(null);
  const [showOpenOnly, setShowOpenOnly] = useState(true);
  const [isCreateOpen, setCreateOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [form, setForm] = useState({
    title: '',
    machineName: '',
    worker: '',
    priority: 'Medium',
    checklistText: '',
    sendEmail: false
  });
  const [gymMachines, setGymMachines] = useState([]);
  const [machinesLoading, setMachinesLoading] = useState(false);
  const [resolveConfirmTicket, setResolveConfirmTicket] = useState(null);
  const createModalRef = useRef(null);
  const createTitleRef = useRef(null);
  const detailsModalRef = useRef(null);
  const resolveModalRef = useRef(null);

  // Backend routing - use backend when available, fallback to local storage
  async function fetchStatus() {
    if (!backendURL) return;
    setLoading(true);
    setErrorMsg('');
    try {
      const gymId = localStorage.getItem('gymId');
      if (!gymId) {
        console.error('No gymId found in localStorage');
        setErrorMsg('No gym selected');
        return;
      }
      
      // Fetch gym-specific tickets directly (this is the main source of truth)
      console.log('Fetching tickets for gym:', gymId);
      const ticketsRes = await fetch(`${backendURL}/api/maintenance/gyms/${gymId}/tickets`);
      if (ticketsRes.ok) {
        const tData = await ticketsRes.json();
        console.log('Tickets response:', tData); // Debug log
        console.log('Number of tickets fetched:', Array.isArray(tData) ? tData.length : 0);
        
        // Debug: Log ticket properties to understand the data structure
        if (Array.isArray(tData) && tData.length > 0) {
          console.log('Sample ticket properties:', Object.keys(tData[0]));
          console.log('Sample ticket data:', tData[0]);
          
          // Log ALL tickets with their complete data structure
          console.log('=== ALL TICKETS DEBUG ===');
          const openTickets = tData.filter(t => t.status === 'open');
          const closedTickets = tData.filter(t => t.status === 'closed');
          console.log(`Status breakdown: ${openTickets.length} open, ${closedTickets.length} closed`);
          
          tData.forEach((ticket, idx) => {
            const isAuto = isAutoTicket(ticket);
            const isManualByFlag = ticket.manual === true;
            console.log(`Ticket ${idx + 1}:`, {
              _id: ticket._id,
              title: ticket.title,
              description: ticket.description,
              status: ticket.status,
              priority: ticket.priority,
              machineName: ticket.machineName,
              worker: ticket.worker,
              manual: ticket.manual,
              ruleKey: ticket.ruleKey,
              ruleInterval: ticket.ruleInterval,
              intervalId: ticket.intervalId,
              isAutoGenerated: ticket.isAutoGenerated,
              createdBy: ticket.createdBy,
              createdAt: ticket.createdAt,
              detectedType: isAuto ? 'Auto' : (isManualByFlag ? 'Manual' : 'Unknown'),
              // Show ALL properties to see what we're missing
              allProperties: Object.keys(ticket),
              // Show one complete ticket to understand structure
              ...(idx === 0 ? { fullTicket: ticket } : {})
            });
          });
          console.log('=== END TICKETS DEBUG ===');
        }
        
        // The endpoint returns an array directly
        if (Array.isArray(tData)) {
          setTickets(tData);
        } else {
          console.warn('Unexpected tickets response format:', tData);
          setTickets([]);
        }
      } else {
        console.error(`Tickets HTTP ${ticketsRes.status}`);
        const errorText = await ticketsRes.text();
        console.error('Tickets error response:', errorText);
        setTickets([]);
      }
      
      // Fetch maintenance statuses (for intervals) - optional
      try {
        const statusRes = await fetch(`${backendURL}/api/maintenance/status?gymId=${gymId}`);
        if (statusRes.ok) {
          const statusData = await statusRes.json();
          setStatuses(Array.isArray(statusData.statuses) ? statusData.statuses : []);
        } else {
          console.warn(`Status HTTP ${statusRes.status}`);
          setStatuses([]);
        }
      } catch (statusError) {
        console.warn('Status fetch failed (non-critical):', statusError);
        setStatuses([]);
      }
    } catch (e) {
      console.error('Fetch status failed', e);
      setErrorMsg(e.message || 'Failed to load');
      setTickets([]);
      setStatuses([]);
    } finally {
      setLoading(false);
    }
  }

  async function fetchGymMachines() {
    if (!backendURL) {
      // Use sample machines if no backend
      setGymMachines(MACHINES.map(m => ({ value: m.name, label: m.name, id: m.id, type: m.type })));
      return;
    }
    
    setMachinesLoading(true);
    try {
      const gymId = localStorage.getItem('gymId');
      if (!gymId) {
        throw new Error('No gym selected');
      }
      
      // FIXED: Use the correct API endpoint
      const res = await fetch(`${backendURL}/api/machines?gymId=${gymId}`);
      if (!res.ok) throw new Error(`Machines HTTP ${res.status}`);
      
      const machines = await res.json();
      const machineOptions = machines.map(m => ({
        value: m.name || m._id,
        label: m.name || `Machine ${m._id}`,
        id: m._id,
        type: m.type || 'Unknown'
      }));
      
      setGymMachines(machineOptions);
    } catch (e) {
      console.error('Failed to fetch gym machines', e);
      // Fallback to sample machines
      setGymMachines(MACHINES.map(m => ({ value: m.name, label: m.name, id: m.id, type: m.type })));
    } finally {
      setMachinesLoading(false);
    }
  }

  async function scanIntervals() {
    setErrorMsg('');
    try {
      const gymId = localStorage.getItem('gymId');
      if (!gymId) {
        throw new Error('No gym selected');
      }
      console.log('Starting scan for gym:', gymId);
      
      const res = await fetch(`${backendURL}/api/maintenance/gyms/${gymId}/scan`, { method: 'POST' });
      
      if (!res.ok) {
        const errorText = await res.text();
        console.error('Scan failed with status:', res.status, 'Response:', errorText);
        throw new Error(`Scan HTTP ${res.status}`);
      }
      
      const scanResult = await res.json();
      console.log('Scan completed successfully:', scanResult);
      
      // Refresh tickets after scan to show any newly created auto-tickets
      await fetchStatus();
    } catch (e) {
      console.error('Scan failed', e);
      setErrorMsg(e.message);
    }
  }

  async function resolveTicket(ticketId) {
    setErrorMsg('');
    setResolveConfirmTicket(null);
    
    // If no backend URL, use local storage
    if (!backendURL) {
      const updatedTickets = tickets.map(t => {
        if (t._id === ticketId) {
          return { ...t, status: 'closed', closedAt: new Date().toISOString() };
        }
        return t;
      });
      setTickets(updatedTickets);
      writeState((curr) => ({ ...curr, tickets: updatedTickets, updatedAt: new Date().toISOString() }));
      return;
    }
    
    // Backend API call
    try {
      const ticket = tickets.find(t => t._id === ticketId);
      let checklistUpdates = [];
      if (ticket && Array.isArray(ticket.checklist)) {
        checklistUpdates = ticket.checklist
          .map(c => {
            if (typeof c === 'string') return { item: c, done: false };
            if (c && typeof c === 'object' && c.item) return { item: c.item, done: !!c.done };
            return null;
          })
          .filter(Boolean);
      }
      const gymId = localStorage.getItem('gymId');
      console.log('Closing ticket:', ticketId, 'for gym:', gymId, 'with checklist updates:', checklistUpdates);
      
      const res = await fetch(`${backendURL}/api/maintenance/tickets/${ticketId}/close`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ checklistUpdates, gymId })
      });
      
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        console.error('Ticket closing failed:', res.status, err);
        throw new Error(err.error || `Close HTTP ${res.status}`);
      }
      
      const result = await res.json();
      console.log('Ticket closed successfully:', result);
      await fetchStatus();
    } catch (e) {
      console.error('Close failed', e);
      setErrorMsg(e.message);
    }
  }

  function toggleChecklistItem(ticketId, idx) {
    const updatedTickets = tickets.map(t => {
      if (t._id !== ticketId) return t;
      const cloned = { ...t };
      cloned.checklist = (cloned.checklist || []).map((item, i) => {
        if (i !== idx) return item;
        if (typeof item === 'string') return { item, done: true };
        return { ...item, done: !item.done };
      });
      return cloned;
    });
    setTickets(updatedTickets);
    
    // If backend is available, we'll sync when closing the ticket or via periodic fetch
    // For now, just update local state (backend can sync on ticket close)
    if (!backendURL) {
      // Persist to local storage when no backend
      writeState((curr) => ({ ...curr, tickets: updatedTickets, updatedAt: new Date().toISOString() }));
    }
  }

  async function onCreate(e) {
    e?.preventDefault?.();
    e?.stopPropagation?.();
    
    if (!form.title || !form.machineName) {
      setErrorMsg('Title and Machine Name are required');
      return;
    }
    
    setErrorMsg('');
    const checklist = form.checklistText
      .split('\n')
      .map(s => s.trim())
      .filter(Boolean);
    
    // If no backend URL, use local storage
    if (!backendURL) {
      const newTicket = {
        _id: `t_${Date.now()}`,
        title: form.title,
        description: form.title,
        machineName: form.machineName,
        worker: form.worker || 'Unassigned',
        priority: form.priority || 'Medium',
        status: 'open',
        manual: true,
        checklist: checklist.map(item => ({ item, done: false })),
        createdAt: new Date().toISOString(),
      };
      const updatedTickets = [newTicket, ...tickets];
      setTickets(updatedTickets);
      writeState((curr) => ({ ...curr, tickets: updatedTickets, updatedAt: new Date().toISOString() }));
      setCreateOpen(false);
      setForm({
        title: '',
        machineName: '',
        worker: '',
        priority: 'Medium',
        checklistText: '',
        sendEmail: false
      });
      return;
    }
    
    // Backend API call
    try {
      const gymId = localStorage.getItem('gymId');
      console.log('Creating ticket for gym:', gymId, 'with data:', {
        title: form.title,
        machineName: form.machineName,
        worker: form.worker || undefined,
        priority: form.priority || 'Medium',
        checklist,
        sendEmail: form.sendEmail
      });
      
      const res = await fetch(`${backendURL}/api/maintenance/tickets`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: form.title,
          machineName: form.machineName,
          worker: form.worker || undefined,
          priority: form.priority || 'Medium',
          checklist,
          sendEmail: form.sendEmail,
          gymId
        })
      });
      
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        console.error('Ticket creation failed:', res.status, err);
        throw new Error(err.error || `Create HTTP ${res.status}`);
      }
      
      const createdTicket = await res.json();
      console.log('Ticket created successfully:', createdTicket);
      await fetchStatus();
      setCreateOpen(false);
      setForm({
        title: '',
        machineName: '',
        worker: '',
        priority: 'Medium',
        checklistText: '',
        sendEmail: false
      });
    } catch (error) {
      console.error('Create failed', error);
      setErrorMsg(error.message || 'Failed to create ticket');
    }
  }

  // Load tickets and machines - use backend when available, fallback to local storage
  useEffect(() => { 
    if (backendURL) {
      fetchStatus();
      fetchGymMachines();
    } else {
      // Load from local storage when no backend
      const s = readState();
      const list = (s.tickets || []);
      setTickets(list);
      fetchGymMachines(); // Still load sample machines
    }
  }, []);

  useEffect(() => {
    if (isCreateOpen) { 
      setTimeout(() => createTitleRef.current?.focus(), 0);
      // Refresh machines list when modal opens
      fetchGymMachines();
    }
  }, [isCreateOpen]);

  // Keyboard handling for resolve modal
  useEffect(() => {
    if (!resolveConfirmTicket) return;
    const trap = (e) => {
      if (e.key === 'Escape') setResolveConfirmTicket(null);
    };
    document.addEventListener('keydown', trap);
    return () => document.removeEventListener('keydown', trap);
  }, [resolveConfirmTicket]);

  // Lock body scroll when any modal is open
  useEffect(() => {
    const hasModal = active || isCreateOpen || resolveConfirmTicket;
    if (hasModal) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [active, isCreateOpen]);

  // Keyboard navigation for details modal
  useEffect(() => {
    if (!active) return;
    const trap = (e) => {
      if (!detailsModalRef.current) return;
      const focusable = detailsModalRef.current.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])');
      if (focusable.length === 0) return;
      const first = focusable[0];
      const last = focusable[focusable.length - 1];
      if (e.key === 'Tab') {
        if (e.shiftKey && document.activeElement === first) { last.focus(); e.preventDefault(); }
        else if (!e.shiftKey && document.activeElement === last) { first.focus(); e.preventDefault(); }
      }
      if (e.key === 'Escape') setActive(null);
    };
    document.addEventListener('keydown', trap);
    return () => document.removeEventListener('keydown', trap);
  }, [active]);

  const openCount = useMemo(() => tickets.filter(t => t.status === 'open').length, [tickets]);

  const sortedTickets = useMemo(() => {
    const arr = [...tickets];
    // Sort by priority first (High > Medium > Low), then by status
    const priorityOrder = { High: 3, Medium: 2, Low: 1 };
    arr.sort((a, b) => {
      if ((a.status === 'open') !== (b.status === 'open')) return a.status === 'open' ? -1 : 1;
      const aPriority = priorityOrder[a.priority] || 2;
      const bPriority = priorityOrder[b.priority] || 2;
      if (aPriority !== bPriority) return bPriority - aPriority; // Higher priority first
      const aAuto = !!a.ruleKey, bAuto = !!b.ruleKey;
      if (aAuto !== bAuto) return aAuto ? -1 : 1;
      if ((a.ruleUnit || '') !== (b.ruleUnit || '')) return (a.ruleUnit || '').localeCompare(b.ruleUnit || '');
      if ((a.ruleInterval || 0) !== (b.ruleInterval || 0)) return (a.ruleInterval || 0) - (b.ruleInterval || 0);
      return (a.dueAtUsage || 0) - (b.dueAtUsage || 0);
    });
    return arr;
  }, [tickets]);

  const visibleTickets = useMemo(
    () => (showOpenOnly ? sortedTickets.filter(t => t.status === 'open') : sortedTickets),
    [sortedTickets, showOpenOnly]
  );

  return (
    <div>
      {/* ... rest of your JSX remains exactly the same ... */}
      <style>{`
        /* Theme the date input and custom dropdown to match site colors */
        .nx-dd { position:relative; }
        .nx-dd-button { display:flex; align-items:center; justify-content:space-between; gap:8px; width:100%; background:#13131a; color:#e5e7eb; border:1px solid #262633; border-radius:8px; padding:8px 10px; height:40px; cursor:pointer; outline:none; }
        .nx-dd-button:focus { border-color:#9b8cfb; outline:4px solid rgba(124,58,237,.18); }
        .nx-dd-menu { position:absolute; top:calc(100% + 8px); left:0; right:0; background:#111119; border:1px solid #1d1d29; border-radius:12px; box-shadow:0 10px 24px rgba(0,0,0,0.45); padding:6px; z-index:60; }
        .nx-dd-item { padding:8px 10px; border-radius:8px; cursor:pointer; color:#e5e7eb; font-size:13px; }
        .nx-dd-item[aria-selected="true"], .nx-dd-item:hover { background:rgba(124,58,237,0.18); color:#c4b5fd; }
        .nx-select { height:40px; }
        .nx-pill { height:32px; cursor:pointer; }

        /* Create Ticket modal refreshed styles */
        .tk-modal { width:min(640px, 80vw) !important; max-width:640px !important; border:1px solid #1d1d29; background:#0f0f16; border-radius:16px; box-shadow:0 20px 60px rgba(0,0,0,.6); overflow:hidden; }
        .tk-header { display:flex; align-items:flex-start; justify-content:space-between; padding:20px 24px; border-bottom:1px solid #1d1d29; }
        .tk-title { font-size:18px; font-weight:600; color:#e5e7eb; }
        .tk-close { display:inline-flex; align-items:center; justify-content:center; width:36px; height:36px; border-radius:10px; color:#a1a1b3; background:transparent; border:1px solid transparent; cursor:pointer; }
        .tk-close:hover { background:#181824; color:#e5e7eb; }
        .tk-close:focus { outline:2px solid rgba(124,58,237,.5); outline-offset:2px; }
        .tk-body { padding:20px 24px; }
        .tk-grid { display:grid; grid-template-columns:1fr; gap:16px; }
        @media (min-width: 768px) { .tk-grid { grid-template-columns:1fr 1fr; gap:18px; } }
        .tk-field { display:flex; flex-direction:column; }
        .tk-label { color:#c7c7d2; font-size:13px; margin-bottom:6px; }
        .tk-helper { color:#8b8ba1; font-size:12px; margin-top:6px; }
        .tk-input { height:44px; border-radius:10px; border:1px solid #262633; background:#13131a; color:#ffffff !important; padding:0 12px; }
        .tk-input::placeholder { color:#7b7b8f; }
        .tk-input:focus { border-color:#9b8cfb; outline:4px solid rgba(124,58,237,.18); color:#ffffff !important; }
        textarea.tk-input { height:auto; padding:12px; resize:vertical; color:#ffffff !important; }
        textarea.tk-input:focus { color:#ffffff !important; }
        .tk-footer-bar { position:sticky; bottom:0; display:flex; justify-content:flex-end; gap:10px; padding:14px 24px; border-top:1px solid #1d1d29; background:#0f0f16; }
        .tk-btn { height:40px; border-radius:10px; padding:0 14px; border:1px solid #2a2a38; color:#e5e7eb; background:#161624; cursor:pointer; }
        .tk-btn:hover { background:#1b1b2b; }
        .tk-btn:focus { outline:2px solid rgba(124,58,237,.5); outline-offset:2px; }
        .tk-btn.primary { background:#7c3aed; border-color:#7c3aed; color:#fff; cursor:pointer; }
        .tk-btn.primary:hover { background:#6d28d9; }
        .tk-btn[disabled] { opacity:.45; cursor:not-allowed; }

        /* Autocomplete dropdown styles */
        .tk-autocomplete { 
          position: absolute; 
          top: calc(100% - 28px); 
          left: 0; 
          right: 0; 
          background: #111119; 
          border: 1px solid #1d1d29; 
          border-radius: 10px; 
          box-shadow: 0 10px 24px rgba(0,0,0,0.45); 
          max-height: 240px; 
          overflow-y: auto; 
          z-index: 70;
        }
        .tk-autocomplete-item { 
          padding: 10px 12px; 
          cursor: pointer; 
          border-bottom: 1px solid #1c1c27;
          transition: background 0.15s ease;
        }
        .tk-autocomplete-item:last-child { 
          border-bottom: none; 
        }
        .tk-autocomplete-item:hover { 
          background: rgba(124,58,237,0.15); 
        }

        /* Highlight matching text - subtle glassy effect */
        .tk-highlight {
          background: rgba(124, 58, 237, 0.12);
          color: #d4c5fd;
          padding: 1px 3px;
          border-radius: 3px;
          border: 1px solid rgba(124, 58, 237, 0.15);
        }

        /* Ticket Details Modal Styles */
        .tk-details-modal {
          width: min(700px, 94vw);
          max-height: 90vh;
          background: #0f0f16;
          border: 1px solid #1d1d29;
          border-radius: 16px;
          overflow: hidden;
          display: flex;
          flex-direction: column;
        }
        .tk-details-header {
          padding: 24px;
          border-bottom: 1px solid #1d1d29;
          background: linear-gradient(135deg, rgba(124, 58, 237, 0.08) 0%, rgba(124, 58, 237, 0.02) 100%);
        }
        .tk-details-title {
          font-size: 20px;
          font-weight: 700;
          color: #ffffff;
          margin-bottom: 12px;
        }
        .tk-details-meta {
          display: flex;
          flex-wrap: wrap;
          gap: 12px;
          align-items: center;
        }
        .tk-details-body {
          flex: 1;
          overflow-y: auto;
          padding: 24px;
        }
        .tk-details-section {
          margin-bottom: 24px;
        }
        .tk-details-section:last-child {
          margin-bottom: 0;
        }
        .tk-details-section-title {
          font-size: 16px;
          font-weight: 600;
          color: #ffffff;
          margin-bottom: 12px;
          display: flex;
          align-items: center;
          gap: 8px;
        }
        .tk-checklist-item {
          padding: 12px;
          background: #13131a;
          border: 1px solid #1d1d29;
          border-radius: 8px;
          margin-bottom: 8px;
          display: flex;
          align-items: flex-start;
          gap: 12px;
        }
        .tk-checklist-item:last-child {
          margin-bottom: 0;
        }
        .tk-checklist-item.completed {
          opacity: 0.6;
        }
        .tk-checklist-checkbox {
          width: 20px;
          height: 20px;
          border: 2px solid #262633;
          border-radius: 4px;
          background: #13131a;
          cursor: pointer;
          flex-shrink: 0;
          margin-top: 2px;
          display: flex;
          align-items: center;
          justify-content: center;
        }
        .tk-checklist-checkbox.checked {
          background: #7c3aed;
          border-color: #7c3aed;
        }
        .tk-checklist-checkbox.checked::after {
          content: '✓';
          color: #fff;
          font-size: 14px;
          font-weight: bold;
        }
        .tk-checklist-text {
          flex: 1;
          color: #e5e7eb;
          font-size: 14px;
          line-height: 1.5;
          white-space: pre-wrap;
          word-break: break-word;
        }
        .tk-details-footer {
          padding: 16px 24px;
          border-top: 1px solid #1d1d29;
          background: #0a0a0f;
          display: flex;
          justify-content: space-between;
          align-items: center;
          gap: 12px;
        }

        /* Consistent ticket width and improved styling */
        .nx-alert-row {
          min-height: 100px;
          padding: 16px;
          border: 1px solid #1d1d29;
          border-radius: 12px;
          background: #13131a;
          margin-bottom: 12px;
          transition: all 0.2s ease;
        }
        .nx-alert-row:hover {
          border-color: #262633;
          background: #151520;
        }
        .nx-alert-row > div:first-child {
          min-width: 0;
          overflow: hidden;
        }
        .tk-ticket-title {
          font-size: 16px;
          font-weight: 600;
          color: #e5e7eb;
          margin-bottom: 8px;
          line-height: 1.4;
        }
        .tk-ticket-meta {
          display: flex;
          flex-wrap: wrap;
          gap: 12px 16px;
          margin-bottom: 8px;
          align-items: center;
        }
        .tk-ticket-meta-item {
          display: flex;
          align-items: center;
          gap: 4px;
          font-size: 12px;
          color: #9ca3af;
        }
        .tk-ticket-meta-label {
          color: #6b7280;
          font-weight: 500;
        }
        .tk-ticket-meta-value {
          color: #cbd5e1;
        }
        .tk-ticket-actions {
          display: flex;
          flex-direction: column;
          gap: 8px;
          flex-shrink: 0;
          align-items: flex-end;
        }
        @media (min-width: 768px) {
          .tk-ticket-actions {
            flex-direction: row;
          }
        }

        /* Resolve Modal Styles */
        .resolve-modal {
          width: min(500px, 90vw);
          background: #0f0f16;
          border: 1px solid #1d1d29;
          border-radius: 16px;
          overflow: hidden;
          position: relative;
        }
        .resolve-close {
          position: absolute;
          top: 16px;
          right: 16px;
          width: 32px;
          height: 32px;
          border-radius: 8px;
          background: transparent;
          border: 1px solid transparent;
          color: #a1a1b3;
          cursor: pointer;
          display: flex;
          align-items: center;
          justify-content: center;
          z-index: 10;
        }
        .resolve-close:hover {
          background: #181824;
          color: #e5e7eb;
        }
        .resolve-header {
          padding: 24px;
          border-bottom: 1px solid #1d1d29;
        }
        .resolve-title {
          font-size: 18px;
          font-weight: 600;
          color: #e5e7eb;
          margin-bottom: 8px;
        }
        .resolve-message {
          color: #a1a1b3;
          font-size: 14px;
          line-height: 1.5;
          margin-bottom: 16px;
        }
        .resolve-ticket-info {
          background: #13131a;
          border: 1px solid #1d1d29;
          border-radius: 8px;
          padding: 16px;
        }
        .resolve-info-row {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 8px;
        }
        .resolve-info-row:last-child {
          margin-bottom: 0;
        }
        .resolve-info-label {
          color: #6b7280;
          font-size: 13px;
          font-weight: 500;
        }
        .resolve-info-value {
          color: #e5e7eb;
          font-size: 13px;
          text-align: right;
          max-width: 60%;
          word-break: break-word;
        }
        .resolve-body {
          padding: 0 24px;
        }
        .resolve-footer {
          padding: 16px 24px;
          border-top: 1px solid #1d1d29;
          display: flex;
          justify-content: flex-end;
          gap: 12px;
        }
        .resolve-btn {
          height: 40px;
          border-radius: 10px;
          padding: 0 16px;
          border: 1px solid #2a2a38;
          color: #e5e7eb;
          background: #161624;
          cursor: pointer;
          font-size: 14px;
          font-weight: 500;
        }
        .resolve-btn:hover {
          background: #1b1b2b;
        }
        .resolve-btn.primary {
          background: #dc2626;
          border-color: #dc2626;
          color: #fff;
        }
        .resolve-btn.primary:hover {
          background: #b91c1c;
        }

        /* Modal overlay */
        .nx-overlay {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: rgba(0, 0, 0, 0.75);
          display: flex;
          align-items: center;
          justify-content: center;
          z-index: 1000;
          padding: 16px;
        }
      `}</style>

      {errorMsg && (
        <div style={{ marginBottom:12, color:'#f87171', fontSize:13 }}>Error: {errorMsg}</div>
      )}

      <div className="nx-card" style={{ marginBottom:16, height:'640px', display:'flex', flexDirection:'column' }}>
        <div className="nx-card-header" style={{ alignItems:'center' }}>
          <div>
            <div className="nx-card-title">Tickets</div>
            <div className="nx-subtle">Open: {openCount} • Total: {tickets.length}</div>
          </div>
          <div style={{ display:'flex', gap:8 }}>
            {/* Backend scan button - shown when backend is available */}
            {backendURL && (
              <button className="nx-pill" onClick={scanIntervals}>Scan Now</button>
            )}
            <button
              className={`nx-pill ${showOpenOnly ? 'primary' : ''}`}
              onClick={() => setShowOpenOnly(!showOpenOnly)}
            >
              {showOpenOnly ? 'Showing Open' : 'Showing All'}
            </button>
            {/* Backend refresh button - shown when backend is available */}
            {backendURL && (
            <button className="nx-pill" onClick={fetchStatus}>Refresh</button>
            )}
            <button className="nx-pill" onClick={() => setCreateOpen(true)}>New Ticket</button>
          </div>
        </div>
        <div style={{ overflow:'auto', borderTop:'1px solid #1c1c27', marginTop:8, paddingTop: 8 }}>
          {visibleTickets.length === 0 && <div className="nx-subtle" style={{ padding: '24px', textAlign: 'center' }}>No tickets yet.</div>}
          {visibleTickets.map(t => (
            <div key={t._id} className="nx-alert-row" style={{ gridTemplateColumns:'1fr auto', alignItems:'flex-start' }}>
              <div style={{ minWidth: 0, overflow: 'hidden', flex: 1 }}>
                <div className="tk-ticket-title">{t.description || t.title}</div>
                <div className="tk-ticket-meta">
                  <div className="tk-ticket-meta-item">
                    <span className="tk-ticket-meta-label">Type:</span>
                    <span className="tk-ticket-meta-value" style={{ 
                      color: isAutoTicket(t) ? '#f59e0b' : '#6366f1',
                      fontWeight: '500',
                      fontSize: '11px',
                      textTransform: 'uppercase',
                      letterSpacing: '0.5px'
                    }}>
                      {isAutoTicket(t) ? 'Auto' : 'Manual'}
                    </span>
                  </div>
                  <div className="tk-ticket-meta-item">
                    <span className="tk-ticket-meta-label">Priority:</span>
                    <PriorityBadge priority={t.priority} size="small" />
                  </div>
                  <div className="tk-ticket-meta-item">
                    <span className="tk-ticket-meta-label">Status:</span>
                    <span className="tk-ticket-meta-value" style={{ 
                      color: t.status === 'open' ? '#22c55e' : t.status === 'closed' ? '#9ca3af' : '#9ca3af',
                      fontWeight: '500'
                    }}>{t.status}</span>
                  </div>
                  {t.machineName && (
                    <div className="tk-ticket-meta-item">
                      <span className="tk-ticket-meta-label">Machine:</span>
                      <span className="tk-ticket-meta-value">{t.machineName}</span>
                    </div>
                  )}
                  {t.worker && t.worker !== 'Unassigned' && (
                    <div className="tk-ticket-meta-item">
                      <span className="tk-ticket-meta-label">Assigned:</span>
                      <span className="tk-ticket-meta-value">{t.worker}</span>
                    </div>
                  )}
                  {t.createdAt && (
                    <div className="tk-ticket-meta-item">
                      <span className="tk-ticket-meta-label">Created:</span>
                      <span className="tk-ticket-meta-value">{new Date(t.createdAt).toLocaleDateString()}</span>
                    </div>
                  )}
                  {t.ruleInterval && (
                    <div className="tk-ticket-meta-item">
                      <span className="tk-ticket-meta-label">Interval:</span>
                      <span className="tk-ticket-meta-value">{t.ruleInterval} {t.ruleUnit || ''}</span>
                    </div>
                  )}
                </div>
                {Array.isArray(t.checklist) && t.checklist.length > 0 && (
                  <div style={{ 
                    marginTop: 8, 
                    fontSize: 12, 
                    color: '#6b7280',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '6px'
                  }}>
                    <svg width="14" height="14" fill="currentColor" viewBox="0 0 20 20" style={{ opacity: 0.6 }}>
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"/>
                    </svg>
                    <span>{t.checklist.length} checklist item{t.checklist.length !== 1 ? 's' : ''} • Click Details to view</span>
                  </div>
                )}
              </div>
              <div className="tk-ticket-actions">
                <button className="nx-pill" onClick={() => setActive(t)} style={{ whiteSpace: 'nowrap' }}>Details</button>
                {t.status === 'open' && (
                  <button className="nx-pill primary" onClick={() => setResolveConfirmTicket(t)} style={{ whiteSpace: 'nowrap' }}>Resolve</button>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Ticket Details Modal */}
      {active && (
        <div className="nx-overlay" onClick={() => setActive(null)}>
          <div ref={detailsModalRef} className="tk-details-modal" onClick={(e) => e.stopPropagation()}>
            <div className="tk-details-header">
              <div className="tk-details-title">{active.description || active.title}</div>
              <div className="tk-details-meta">
                <div style={{ 
                  color: isAutoTicket(active) ? '#f59e0b' : '#6366f1',
                  fontWeight: '500',
                  fontSize: '12px',
                  textTransform: 'uppercase',
                  letterSpacing: '0.5px',
                  background: isAutoTicket(active) ? 'rgba(245, 158, 11, 0.15)' : 'rgba(99, 102, 241, 0.15)',
                  padding: '4px 8px',
                  borderRadius: '6px',
                  border: `1px solid ${isAutoTicket(active) ? 'rgba(245, 158, 11, 0.35)' : 'rgba(99, 102, 241, 0.35)'}`
                }}>
                  {isAutoTicket(active) ? 'Auto' : 'Manual'}
                </div>
                <PriorityBadge priority={active.priority} />
                <div style={{ 
                  color: active.status === 'open' ? '#22c55e' : active.status === 'closed' ? '#9ca3af' : '#9ca3af',
                  fontWeight: '500',
                  fontSize: '12px',
                  textTransform: 'capitalize'
                }}>
                  {active.status}
                </div>
              </div>
            </div>
            <div className="tk-details-body">
              <div className="tk-details-section">
                <div className="tk-details-section-title">
                  <svg width="16" height="16" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"/>
                  </svg>
                  Details
                </div>
                <div style={{ color: '#cbd5e1', fontSize: '14px', lineHeight: '1.6' }}>
                  <div style={{ marginBottom: '12px' }}>
                    <strong style={{ color: '#e5e7eb' }}>Machine:</strong> {active.machineName || 'Not specified'}
                  </div>
                  {active.worker && active.worker !== 'Unassigned' && (
                    <div style={{ marginBottom: '12px' }}>
                      <strong style={{ color: '#e5e7eb' }}>Assigned to:</strong> {active.worker}
                    </div>
                  )}
                  {active.createdAt && (
                    <div style={{ marginBottom: '12px' }}>
                      <strong style={{ color: '#e5e7eb' }}>Created:</strong> {new Date(active.createdAt).toLocaleDateString()}
                    </div>
                  )}
                  {active.ruleInterval && (
                    <div style={{ marginBottom: '12px' }}>
                      <strong style={{ color: '#e5e7eb' }}>Maintenance Interval:</strong> {active.ruleInterval} {active.ruleUnit || ''}
                    </div>
                  )}
                </div>
              </div>

              {Array.isArray(active.checklist) && active.checklist.length > 0 && (
                <div className="tk-details-section">
                  <div className="tk-details-section-title">
                    <svg width="16" height="16" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"/>
                    </svg>
                    Checklist ({active.checklist.filter(item => {
                      const obj = typeof item === 'string' ? { item, done: false } : item;
                      return obj.done === true;
                    }).length}/{active.checklist.length} completed)
                  </div>
                  <div>
                    {active.checklist.map((item, idx) => {
                      const obj = typeof item === 'string' ? { item, done: false } : item;
                      return (
                        <div 
                          key={idx} 
                          className={`tk-checklist-item ${obj.done ? 'completed' : ''}`}
                        >
                          <div 
                            className={`tk-checklist-checkbox ${obj.done ? 'checked' : ''}`}
                            style={{ cursor: active.status === 'open' ? 'pointer' : 'default' }}
                            onClick={() => {
                              if (active.status === 'open') {
                                toggleChecklistItem(active._id, idx);
                              }
                            }}
                          />
                          <div className="tk-checklist-text">{obj.item}</div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}
            </div>
            <div className="tk-details-footer">
              <button 
                className="tk-btn" 
                onClick={() => setActive(null)}
              >
                Close
              </button>
              {active.status === 'open' && (
                <button 
                  className="tk-btn primary" 
                  onClick={() => {
                    setActive(null);
                    setResolveConfirmTicket(active);
                  }}
                >
                  Resolve Ticket
                </button>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Create Ticket Modal */}
      {isCreateOpen && (
        <div className="nx-overlay" onClick={() => setCreateOpen(false)}>
          <div ref={createModalRef} className="tk-modal" onClick={(e) => e.stopPropagation()}>
            <div className="tk-header">
              <div className="tk-title">Create New Ticket</div>
              <button className="tk-close" onClick={() => setCreateOpen(false)} aria-label="Close">
                <svg width="16" height="16" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"/>
                </svg>
              </button>
            </div>
            <form onSubmit={onCreate}>
              <div className="tk-body">
                <div className="tk-grid">
                  <div className="tk-field" style={{ gridColumn: '1 / -1' }}>
                    <label className="tk-label">Title *</label>
                    <input
                      ref={createTitleRef}
                      type="text"
                      className="tk-input"
                      placeholder="Brief description of the issue"
                      value={form.title}
                      onChange={(e) => setForm(prev => ({ ...prev, title: e.target.value }))}
                      required
                    />
                  </div>
                  
                  <div className="tk-field">
                    <label className="tk-label">Machine Name *</label>
                    <MachineAutocomplete
                      value={form.machineName}
                      onChange={(value) => setForm(prev => ({ ...prev, machineName: value }))}
                      machines={gymMachines}
                      loading={machinesLoading}
                    />
                  </div>
                  
                  <div className="tk-field">
                    <label className="tk-label">Assigned Worker</label>
                    <input
                      type="text"
                      className="tk-input"
                      placeholder="Optional"
                      value={form.worker}
                      onChange={(e) => setForm(prev => ({ ...prev, worker: e.target.value }))}
                    />
                  </div>
                  
                  <div className="tk-field">
                    <label className="tk-label">Priority</label>
                    <TicketDropdown
                      value={form.priority}
                      onChange={(value) => setForm(prev => ({ ...prev, priority: value }))}
                      options={[
                        { value: 'Low', label: 'Low Priority' },
                        { value: 'Medium', label: 'Medium Priority' },
                        { value: 'High', label: 'High Priority' }
                      ]}
                    />
                  </div>
                  
                  <div className="tk-field" style={{ gridColumn: '1 / -1' }}>
                    <label className="tk-label">Checklist</label>
                    <textarea
                      className="tk-input"
                      style={{ height: '120px', resize: 'vertical', padding: '12px' }}
                      placeholder="Enter checklist items (one per line)&#10;Example:&#10;Check equipment power&#10;Inspect for damage&#10;Test functionality"
                      value={form.checklistText}
                      onChange={(e) => setForm(prev => ({ ...prev, checklistText: e.target.value }))}
                    />
                    <div className="tk-helper">Enter each checklist item on a new line</div>
                  </div>
                  
                  {/* <div className="tk-field" style={{ gridColumn: '1 / -1' }}>
                    <label style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' }}>
                      <input
                        type="checkbox"
                        checked={form.sendEmail}
                        onChange={(e) => setForm(prev => ({ ...prev, sendEmail: e.target.checked }))}
                        style={{ width: '16px', height: '16px' }}
                      />
                      <span className="tk-label" style={{ margin: 0 }}>Send email notification</span>
                    </label>
                  </div> */}
                </div>
              </div>
              <div className="tk-footer-bar">
                <button type="button" className="tk-btn" onClick={() => setCreateOpen(false)}>
                  Cancel
                </button>
                <button type="submit" className="tk-btn primary">
                  Create Ticket
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Resolve Confirmation Modal */}
      {resolveConfirmTicket && (
        <div className="nx-overlay" onClick={() => setResolveConfirmTicket(null)}>
          <div ref={resolveModalRef} className="resolve-modal" onClick={(e) => e.stopPropagation()}>
            <button className="resolve-close" onClick={() => setResolveConfirmTicket(null)} aria-label="Close">
              <svg width="16" height="16" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"/>
              </svg>
            </button>
            <div className="resolve-header">
              <div className="resolve-title">Close Ticket</div>
              <div className="resolve-message">
                Are you sure you want to close this task? This action will mark the ticket as closed.
              </div>
              <div className="resolve-ticket-info">
                <div className="resolve-info-row">
                  <span className="resolve-info-label">Title:</span>
                  <span className="resolve-info-value">{resolveConfirmTicket.description || resolveConfirmTicket.title}</span>
                </div>
                {resolveConfirmTicket.machineName && (
                  <div className="resolve-info-row">
                    <span className="resolve-info-label">Machine:</span>
                    <span className="resolve-info-value">{resolveConfirmTicket.machineName}</span>
                  </div>
                )}
                <div className="resolve-info-row">
                  <span className="resolve-info-label">Priority:</span>
                  <span className="resolve-info-value">
                    <PriorityBadge priority={resolveConfirmTicket.priority} />
                  </span>
                </div>
                {resolveConfirmTicket.worker && (
                  <div className="resolve-info-row">
                    <span className="resolve-info-label">Assigned To:</span>
                    <span className="resolve-info-value">{resolveConfirmTicket.worker}</span>
                  </div>
                )}
                {Array.isArray(resolveConfirmTicket.checklist) && resolveConfirmTicket.checklist.length > 0 && (
                  <div className="resolve-info-row">
                    <span className="resolve-info-label">Checklist:</span>
                    <span className="resolve-info-value">
                      {resolveConfirmTicket.checklist.filter(item => {
                        const obj = typeof item === 'string' ? { item, done: false } : item;
                        return obj.done === true;
                      }).length} / {resolveConfirmTicket.checklist.length} completed
                    </span>
                  </div>
                )}
              </div>
            </div>
            <div className="resolve-body">
              {/* Additional confirmation message could go here */}
            </div>
            <div className="resolve-footer">
              <button 
                className="resolve-btn" 
                onClick={() => setResolveConfirmTicket(null)}
              >
                Cancel
              </button>
              <button 
                className="resolve-btn primary" 
                onClick={() => resolveTicket(resolveConfirmTicket._id)}
              >
                Close Ticket
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// Local dropdown for the modal
function TicketDropdown({ value, onChange, options, disabled = false }) {
  const [open, setOpen] = React.useState(false);
  const ref = React.useRef(null);
  React.useEffect(() => {
    const onDoc = (e) => { if (ref.current && !ref.current.contains(e.target)) setOpen(false); };
    document.addEventListener('mousedown', onDoc);
    return () => document.removeEventListener('mousedown', onDoc);
  }, []);
  const selected = options.find(o => String(o.value) === String(value)) || options[0];
  return (
    <div className="nx-dd" ref={ref}>
      <button 
        className="nx-dd-button" 
        onClick={()=>!disabled && setOpen(o=>!o)} 
        aria-haspopup="listbox" 
        aria-expanded={open}
        disabled={disabled}
        style={{
          opacity: disabled ? 0.6 : 1,
          cursor: disabled ? 'not-allowed' : 'pointer'
        }}
      >
        <span>{selected?.label}</span>
        <span style={{opacity:.8}}>▾</span>
      </button>
      {open && !disabled && (
        <div className="nx-dd-menu" role="listbox">
          {options.map(opt => (
            <div key={String(opt.value)} className="nx-dd-item" role="option" aria-selected={String(opt.value)===String(value)} onClick={()=>{ onChange(opt.value); setOpen(false); }}>
              {opt.label}
                  </div>
                ))}
        </div>
      )}
    </div>
  );
}

// Machine autocomplete component for create modal
function MachineAutocomplete({ value, onChange, machines, loading }) {
  const [query, setQuery] = useState('');
  const [isOpen, setIsOpen] = useState(false);
  const [highlightedIndex, setHighlightedIndex] = useState(0);
  const inputRef = useRef(null);
  const listRef = useRef(null);

  const filteredMachines = useMemo(() => {
    if (!query) return machines.slice(0, 10);
    return machines
      .filter(m => m.label.toLowerCase().includes(query.toLowerCase()))
      .slice(0, 10);
  }, [machines, query]);

  useEffect(() => {
    if (isOpen && filteredMachines.length > 0) {
      setHighlightedIndex(0);
    }
  }, [filteredMachines, isOpen]);

  const handleKeyDown = (e) => {
    if (!isOpen) {
      if (e.key === 'ArrowDown' || e.key === 'Enter') {
        setIsOpen(true);
        e.preventDefault();
      }
      return;
    }

    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault();
        setHighlightedIndex(prev => 
          prev < filteredMachines.length - 1 ? prev + 1 : 0
        );
        break;
      case 'ArrowUp':
        e.preventDefault();
        setHighlightedIndex(prev => 
          prev > 0 ? prev - 1 : filteredMachines.length - 1
        );
        break;
      case 'Enter':
        e.preventDefault();
        if (filteredMachines[highlightedIndex]) {
          selectMachine(filteredMachines[highlightedIndex]);
        }
        break;
      case 'Escape':
        setIsOpen(false);
        inputRef.current?.blur();
        break;
    }
  };

  const selectMachine = (machine) => {
    onChange(machine.value);
    setQuery(machine.value);
    setIsOpen(false);
  };

  useEffect(() => {
    setQuery(value);
  }, [value]);

  useEffect(() => {
    const handleClickOutside = (e) => {
      if (inputRef.current && !inputRef.current.contains(e.target)) {
        setIsOpen(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  return (
    <div style={{ position: 'relative' }} ref={inputRef}>
      <input
        type="text"
        className="tk-input"
        placeholder={loading ? "Loading machines..." : "Type to search machines..."}
        value={query}
        onChange={(e) => {
          setQuery(e.target.value);
          onChange(e.target.value);
          setIsOpen(true);
        }}
        onKeyDown={handleKeyDown}
        onFocus={() => setIsOpen(true)}
        disabled={loading}
        required
      />
      {isOpen && !loading && filteredMachines.length > 0 && (
        <div className="tk-autocomplete" ref={listRef}>
          {filteredMachines.map((machine, index) => (
            <div
              key={machine.id}
              className="tk-autocomplete-item"
              style={{
                background: index === highlightedIndex ? 'rgba(124,58,237,0.15)' : 'transparent'
              }}
              onClick={() => selectMachine(machine)}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <HighlightMatch text={machine.label} query={query} />
                <span style={{ fontSize: '11px', color: '#6b7280', marginLeft: '8px' }}>
                  {machine.type}
                </span>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}