name: Build and Deploy Docker Image to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch full git history and latest commit SHA

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: onsight.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          COMMIT_SHA=${{ github.sha }}
          echo "Building Docker image with commit SHA $COMMIT_SHA"
          docker build \
            --no-cache \
            --build-arg VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }} \
            -t onsight.azurecr.io/onsight-frontend:latest \
            -t onsight.azurecr.io/onsight-frontend:$COMMIT_SHA .
          docker push onsight.azurecr.io/onsight-frontend:latest
          docker push onsight.azurecr.io/onsight-frontend:$COMMIT_SHA

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: onsight-frontend
          images: onsight.azurecr.io/onsight-frontend:latest
